import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

const text = (v) => (v == null ? '' : String(v))

function buildPdf(p) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' })
  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 40
  let y = margin

  // Header
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(18)
  doc.text('Medical Prescription', margin, y)

  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  const rightX = pageWidth - margin
  ;[
    `Date: ${text(p.prescriptionDate)}`,
    `Doctor: ${text(p.doctorName)}`,
    `Prescription ID: ${text(p.id)}`,
  ].forEach((line, i) => doc.text(line, rightX, y + i * 14, { align: 'right' }))

  y += 28
  doc.setDrawColor(200)
  doc.line(margin, y, pageWidth - margin, y)
  y += 16

  // Patient info
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(12)
  doc.text('Patient Information', margin, y)
  y += 12
  doc.setFont('helvetica', 'normal')
  ;[
    `Name: ${text(p.patientName)}`,
    `Age: ${text(p.patientAge)}  |  Gender: ${text(p.patientGender)}`,
    `Phone: ${text(p.patientPhone)}`,
    `Email: ${text(p.patientEmail)}`,
  ].forEach((line) => { y += 14; doc.text(line, margin, y) })

  y += 18
  doc.setDrawColor(230)
  doc.line(margin, y, pageWidth - margin, y)
  y += 18

  // Diagnosis & Symptoms
  if (text(p.diagnosis) || text(p.symptoms)) {
    doc.setFont('helvetica', 'bold')
    doc.text('Diagnosis & Symptoms', margin, y)
    y += 14
    doc.setFont('helvetica', 'normal')

    if (text(p.diagnosis)) {
      const split = doc.splitTextToSize(`Diagnosis: ${text(p.diagnosis)}`, pageWidth - margin * 2)
      doc.text(split, margin, y)
      y += 14 + (split.length - 1) * 12
    }
    if (text(p.symptoms)) {
      const split = doc.splitTextToSize(`Symptoms: ${text(p.symptoms)}`, pageWidth - margin * 2)
      doc.text(split, margin, y)
      y += 14 + (split.length - 1) * 12
    }
    y += 6
  }

  // Medicines
  const meds = Array.isArray(p.medicines) ? p.medicines : []
  if (meds.length) {
    doc.setFont('helvetica', 'bold')
    doc.text(`Prescribed Medicines (${meds.length})`, margin, y)
    autoTable(doc, {
      startY: y + 8,
      head: [[
        'No.', 'Name', 'Dosage', 'Frequency', 'Duration', 'Timing', 'Special Instructions'
      ]],
      body: meds.map((m, i) => [
        String(i + 1),
        text(m.name),
        text(m.dosage),
        text(m.frequency),
        text(m.duration),
        text(m.timing),
        text(m.specialInstructions)
      ]),
      styles: { font: 'helvetica', fontSize: 9, cellPadding: 4 },
      headStyles: { fillColor: [59, 130, 246], textColor: 255 },
      alternateRowStyles: { fillColor: [245, 247, 250] },
      tableLineColor: [220, 220, 220],
      tableLineWidth: 0.5,
      margin: { left: margin, right: margin }
    })
    y = doc.lastAutoTable.finalY + 12
  }

  // Instructions & Follow-up
  if (text(p.instructions) || text(p.followUpDate) || text(p.notes)) {
    doc.setFont('helvetica', 'bold')
    doc.text('Instructions & Follow-up', margin, y)
    y += 14
    doc.setFont('helvetica', 'normal')
    if (text(p.instructions)) {
      const split = doc.splitTextToSize(`General Instructions: ${text(p.instructions)}`, pageWidth - margin * 2)
      doc.text(split, margin, y)
      y += 14 + (split.length - 1) * 12
    }
    if (text(p.followUpDate)) {
      doc.text(`Follow-up Date: ${text(p.followUpDate)}`, margin, y)
      y += 14
    }
    if (text(p.notes)) {
      const split = doc.splitTextToSize(`Additional Notes: ${text(p.notes)}`, pageWidth - margin * 2)
      doc.text(split, margin, y)
      y += 14 + (split.length - 1) * 12
    }
  }

  // Footer
  y += 12
  doc.setDrawColor(200)
  doc.line(margin, y, pageWidth - margin, y)
  y += 10
  doc.setFontSize(9)
  doc.text('Generated by Clinic Management System', margin, y)

  return doc
}

export function downloadPrescriptionPDF(prescription) {
  try {
    const doc = buildPdf(prescription)
    const filename = `Prescription_${(prescription?.patientName || 'patient').replace(/\s+/g, '_')}_${prescription?.prescriptionDate || ''}.pdf`
    doc.save(filename)
    return true
  } catch (e) {
    console.error('downloadPrescriptionPDF error:', e)
    return false
  }
}

export function openPrescriptionPDF(prescription) {
  try {
    const doc = buildPdf(prescription)
    const blob = doc.output('blob')
    const url = URL.createObjectURL(blob)
    window.open(url, '_blank')
    return true
  } catch (e) {
    console.error('openPrescriptionPDF error:', e)
    return false
  }
}

export function printPrescriptionPDF(prescription) {
  try {
    const doc = buildPdf(prescription)
    const blob = doc.output('blob')
    const url = URL.createObjectURL(blob)
    const w = window.open(url)
    if (w) {
      const listener = () => {
        w.focus()
        w.print()
        w.removeEventListener('load', listener)
      }
      w.addEventListener('load', listener)
    }
    return true
  } catch (e) {
    console.error('printPrescriptionPDF error:', e)
    return false
  }
}
